# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-26 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppCodeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('My_file', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('projectName', models.TextField(primary_key=True, serialize=False)),
                ('totalScore', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Screens',
            fields=[
                ('scrID', models.IntegerField(primary_key=True, serialize=False)),
                ('bky', models.TextField()),
                ('scm', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('userProjects', models.ManyToManyField(to='myAnalyzer.Projects')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='screens',
            field=models.ManyToManyField(to='myAnalyzer.Screens'),
        ),
    ]
