# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-27 15:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myAnalyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='userFolder',
            field=models.TextField(default=datetime.datetime(2016, 9, 27, 15, 40, 38, 240714, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
