# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-28 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAnalyzer', '0002_users_userfolder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='userFolder',
        ),
    ]
