# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-26 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAnalyzer', '0004_updateuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateuser',
            name='lastname',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='updateuser',
            name='username',
            field=models.CharField(max_length=254),
        ),
    ]
