# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-26 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAnalyzer', '0005_auto_20161226_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updateuser',
            old_name='username',
            new_name='firstname',
        ),
    ]
