# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-26 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAnalyzer', '0006_auto_20161226_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updateuser',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='updateuser',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
