# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-26 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAnalyzer', '0007_auto_20161226_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='userProjects',
            new_name='projects',
        ),
    ]
