# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-28 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAnalyzer', '0009_auto_20170128_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='appinventorLogin',
            field=models.CharField(max_length=254),
        ),
    ]
