# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAnalyzer', '0014_auto_20170128_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screens',
            name='scrID',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
