# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAnalyzer', '0015_auto_20170218_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='totalScore',
        ),
    ]
